language: csharp  
sudo: required  
dotnet: 2.0.0
dist: trusty  
env:  
  - CLI_VERSION=latest
addons:  
  apt:
  sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5
mono: none
os:  
  - linux  
branches:  
  only:
    - master
  
#before_install:  
 # - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fiopenssl; fi
#install:  
 # - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
 # - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
 # - export PATH="$DOTNET_INSTALL_DIR:$PATH"  
#script:  
 # - ./build.sh