FROM microsoft/dotnet
LABEL maintainer="Joe"

# Create a directory where our app will be placed
RUN mkdir -p /usr/

WORKDIR /usr/

RUN apt-get update 
RUN apt-get install -y git php5-curl curl php5-cli vim

#Copy the source COPY source dest
#COPY . /usr/smooth/
RUN git clone https://github.com/jbrach/smooth.git

WORKDIR /user/smooth/

RUN dotnet restore

RUN dotnet build

WORKDIR ./test/

RUN dotnet test


# run tests on docker run
ENTRYPOINT ["top", "-b"]
CMD ["-c"]