FROM microsoft/dotnet

WORKDIR /smooth/


COPY . .

RUN ls

WORKDIR test/

RUN ls

RUN dotnet restore

# run tests on docker build
RUN dotnet test

# run tests on docker run
ENTRYPOINT ["dotnet", "test"]