
#Docker Command to create volume smooth-data on the busybox container
docker create -v /var/lib/postgresql/data --name smooth-data busybox

#link the volumn to the lastest postgres image
docker run --name local-postgres -e POSTGRES_PASSWORD=password -d  --volumes-from smooth-data postgres
#Important that the port is linked correctly.   Add -p 5432:5432 to above and was able to connect to docker container. 
docker run --name local-postgres -e POSTGRES_PASSWORD=password -d -p 5432:5432 --volumes-from smooth-data postgres 

#run it ..  need to research this one.   
docker run -it --link local-postgres:postgres --rm postgres sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres'